# Generated by Django 5.0.4 on 2024-05-05 23:41

import events.services.validate_rating
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, validators=[events.services.validate_rating.validate_rating]),
        ),
    ]
