version: '3.8'

services:
  postgres-db:
    image: postgres:16
    container_name: podiya_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: podiya
    ports:
      - "5432:5432"
    networks:
      - prediction-network
    volumes:
      - pg_data:/var/lib/postgresql/data

  podiya:
    container_name: podiya_backend
    build:
      context: .
    volumes:
      - static_volume:/app/static
    ports:
      - "8000:8000"
    depends_on:
      - postgres-db
    networks:
      - prediction-network

  nginx:
    image: nginx:latest
    container_name: podiya_nginx
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/static
    ports:
      - "80:80"
    depends_on:
      - podiya
    networks:
      - prediction-network

  redis:
    image: redis:latest
    container_name: podiya_redis
    ports:
      - "6379:6379"
    networks:
      - prediction-network

volumes:
  pg_data:
  static_volume:


networks:
  prediction-network:
    driver: bridge