# Generated by Django 5.0.4 on 2024-05-07 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatars/no_avatar.webp', upload_to='avatars/'),
        ),
    ]
